# Generated by Django 2.1.7 on 2020-12-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
