# Generated by Django 2.1.7 on 2020-12-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0003_delete_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
