# Generated by Django 2.1.7 on 2020-12-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0004_auto_20201213_1555'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
