# Generated by Django 2.1.7 on 2020-12-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0005_auto_20201213_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Blogger',
        ),
    ]
