# Generated by Django 2.1.7 on 2020-12-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0006_auto_20201213_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
