# Generated by Django 2.1.7 on 2020-12-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0007_auto_20201213_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
