# Generated by Django 2.1.7 on 2020-12-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0008_auto_20201213_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='created_on',
        ),
    ]
